# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-10-31 05:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('ip', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=1024)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('UA', models.CharField(max_length=1024)),
                ('ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gitblog.Address')),
            ],
        ),
    ]
